import type { Product } from "@/types/product";

export const demoProducts: Product[] = [
  {
    id: "prod_001",
    title: "Starter Crystal Pack",
    gameTitle: "Shadow Realm Online",
    sku: "SRO-CRY-ST01",
    productType: "Virtual Currency",
    price: 4.99,
    currency: "USD",
    status: "live",
    region: "NA / EU",
    webhookUrl: "https://hooks.demo.merchant/shadow-realm/purchase",
    supportEmail: "billing@shadowrealm-demo.io",
    readinessScore: 100,
    issues: [],
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "prod_002",
    title: "Season Pass Q3",
    gameTitle: "Mecha Rush Arena",
    sku: "MRA-BP-Q3-26",
    productType: "Battle Pass",
    price: 14.99,
    currency: "USD",
    status: "review",
    region: "Global",
    webhookUrl: "https://hooks.demo.merchant/mecha-rush/battle-pass",
    supportEmail: "passes@mecharush-demo.io",
    readinessScore: 72,
    issues: [
      {
        id: "iss_201",
        message: "Tier reward manifest not uploaded for EU storefront",
        severity: "high",
      },
      {
        id: "iss_202",
        message: "Marketing copy pending legal review",
        severity: "medium",
      },
    ],
    createdAt: "2026-03-05T14:30:00Z",
  },
  {
    id: "prod_003",
    title: "Founder Bundle",
    gameTitle: "Kingdom Forge",
    sku: "KF-DLC-FOUNDER",
    productType: "DLC Bundle",
    price: 39.99,
    currency: "USD",
    status: "staging",
    region: "NA",
    webhookUrl: "https://hooks.demo.merchant/kingdom-forge/founder",
    supportEmail: "founders@kingdomforge-demo.io",
    readinessScore: 85,
    issues: [
      {
        id: "iss_301",
        message: "Staging webhook secret not rotated after last deploy",
        severity: "medium",
      },
    ],
    createdAt: "2026-02-18T09:15:00Z",
  },
  {
    id: "prod_004",
    title: "Premium Car Skin",
    gameTitle: "Neon Drift League",
    sku: "NDL-COS-CAR-PRM",
    productType: "Cosmetic Item",
    price: 7.99,
    currency: "EUR",
    status: "live",
    region: "EU",
    webhookUrl: "https://hooks.demo.merchant/neon-drift/cosmetics",
    supportEmail: "store@neondrift-demo.io",
    readinessScore: 96,
    issues: [
      {
        id: "iss_401",
        message: "Asset CDN cache TTL below recommended threshold",
        severity: "low",
      },
    ],
    createdAt: "2025-11-20T16:45:00Z",
  },
  {
    id: "prod_005",
    title: "500 Gem Pack",
    gameTitle: "Dragonvale Tactics",
    sku: "DVT-VC-GEM500",
    productType: "Virtual Currency",
    price: 9.99,
    currency: "USD",
    status: "draft",
    region: "APAC",
    webhookUrl: "",
    supportEmail: "commerce@dragonvale-demo.io",
    readinessScore: 34,
    issues: [
      {
        id: "iss_501",
        message: "Webhook URL is required before staging",
        severity: "high",
      },
      {
        id: "iss_502",
        message: "APAC price tier not configured",
        severity: "high",
      },
      {
        id: "iss_503",
        message: "SKU not registered in entitlement service",
        severity: "medium",
      },
    ],
    createdAt: "2026-05-10T11:00:00Z",
  },
  {
    id: "prod_006",
    title: "Monthly VIP Pass",
    gameTitle: "Pixel Farm World",
    sku: "PFW-SUB-VIP-MO",
    productType: "Subscription",
    price: 12.99,
    currency: "USD",
    status: "blocked",
    region: "LATAM",
    webhookUrl: "https://hooks.demo.merchant/pixel-farm/subscription",
    supportEmail: "vip@pixelfarm-demo.io",
    readinessScore: 48,
    issues: [
      {
        id: "iss_601",
        message: "Recurring billing profile failed compliance check",
        severity: "high",
      },
      {
        id: "iss_602",
        message: "LATAM tax category missing for subscription SKU",
        severity: "high",
      },
      {
        id: "iss_603",
        message: "Cancellation policy URL returns 404",
        severity: "medium",
      },
    ],
    createdAt: "2026-04-02T08:20:00Z",
  },
  {
    id: "prod_007",
    title: "Deluxe Raid Key",
    gameTitle: "Shadow Realm Online",
    sku: "SRO-KEY-RAID-DX",
    productType: "Game Key",
    price: 24.99,
    currency: "USD",
    status: "staging",
    region: "Global",
    webhookUrl: "https://hooks.demo.merchant/shadow-realm/keys",
    supportEmail: "keys@shadowrealm-demo.io",
    readinessScore: 78,
    issues: [
      {
        id: "iss_701",
        message: "Key pool inventory below minimum for Global region",
        severity: "medium",
      },
    ],
    createdAt: "2026-04-28T13:10:00Z",
  },
  {
    id: "prod_008",
    title: "Mecha Starter Crate",
    gameTitle: "Mecha Rush Arena",
    sku: "MRA-DLC-START-01",
    productType: "DLC Bundle",
    price: 19.99,
    currency: "GBP",
    status: "draft",
    region: "UK",
    webhookUrl: "https://hooks.demo.merchant/mecha-rush/starter",
    supportEmail: "support@mecharush-demo.io",
    readinessScore: 55,
    issues: [
      {
        id: "iss_801",
        message: "Bundle contents JSON missing two reward items",
        severity: "medium",
      },
      {
        id: "iss_802",
        message: "GBP price not synced to regional catalog",
        severity: "low",
      },
    ],
    createdAt: "2026-05-18T17:00:00Z",
  },
];

export function getProductById(id: string): Product | undefined {
  return demoProducts.find((product) => product.id === id);
}

export function getAllProducts(): Product[] {
  return demoProducts;
}
